apiVersion: v1
kind: Service
metadata:
  name: service
  namespace: system
  labels:
    control-plane: addon-manager
spec:
  selector:
    control-plane: addon-manager
  ports:
    - port: 8443
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: addon-manager-configmap
  namespace: addon-manager-system
data:
  addon-manager-controller.yaml: |
    addon-namespaces:
      addon-active-monitor-ns
      addon-alb-ingress-controller-ns
      addon-chaos-system
      addon-cluster-autoscaler-ns
      addon-event-router-ns
      addon-external-dns-ns
      addon-lifecycle-manager-ns
      addon-manager-system
      addon-nodereaper-ns
      addon-pdbreaper-ns
      addon-podreaper-ns
      addon-upgrademgr-ns
      addon-wavefront-s3-adapter-ns
      addon-wavefrontcollectors-ns
      addon-gpu-ns
      addon-hpa-algo-ns
      iam-manager-system
      addon-kube-forensics-system-ns
      addon-efs-csi-ns
      addon-oil-ns
      addon-metricset-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
  namespace: system
  labels:
    control-plane: addon-manager
spec:
  selector:
    matchLabels:
      control-plane: addon-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: addon-manager
    spec:
      containers:
      - command:
        - /manager
        args:
        - --enable-leader-election
        image: keikoproj/addon-manager:latest
        name: manager
        volumeMounts:
        - name: config-volume
          mountPath: /etc/manager
        resources:
          requests:
            cpu: 100m
            memory: 20Mi
      volumes:
      - configMap:
          items:
          - key: addon-manager-controller.yaml
            path: addon-manager-controller.yaml
          name: addon-manager-configmap
        name: config-volume
      terminationGracePeriodSeconds: 10
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: workflow-installer-sa
  namespace: system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: addon-workflow-cr
rules:
  - apiGroups: ["rbac.authorization.k8s.io", ""]
    resources: ["namespaces", "clusterroles", "clusterrolebindings", "configmaps", "events", "pods", "serviceaccounts"]
    verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]
  - apiGroups: ["apps", "extensions"]
    resources: ["deployments", "daemonsets", "statefulsets", "replicasets", "ingresses", "controllerrevisions", "customresourcedefinitions"]
    verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["get", "watch", "list", "create", "update", "patch"]
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: addon-workflow-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: addon-workflow-cr
subjects:
  - kind: ServiceAccount
    name: workflow-installer-sa
    namespace: system
